language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-google-app-engine-fullstack' ]; then cd .. && eval "mv $currentfolder generator-google-app-engine-fullstack" && cd generator-google-app-engine-fullstack; fi
